server:
  port: 8081
spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?characterEncoding=utf8
    username: root
    password: 123456
    #springboot自带连接池
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存活最大时间，默认600000(10分钟)
      idle-timeout: 180000
      #最大连接数，默认10
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      #连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  redis:
    #超时时间
    timeout: 10000ms
    #服务器地址
    host: localhost
    #服务器端口
    port: 6379
    #数据库
    database: 0
    lettuce:
      pool:
        #最大连接数默认8
        max-active: 1024
        #最大阻塞等待时间默认-1
        max-wait: 10000ms
        #最大空闲时间
        max-idle: 200
        #最小空闲时间
        min-idle: 5
  #rabbitmq配置
  rabbitmq:
    #用户名
    username: guest
    #密码
    password: guest
    #服务器地址
    host: 127.0.0.1
    #端口
    port: 5672
    #消息确认回调
    publisher-confirm-type: correlated
    #消息失败回调
    publisher-returns: true
#mybatis-plus配置
mybatis-plus:
  #配置mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置mybatis数据返回类型别名（默认别名时类名）
  type-aliases-package: com.hdd.server.pojo
  configuration:
    #自动驼峰命名
    map-underscore-to-camel-case: false

#mybatis sql 打印（方法接口所在的包，不是mapper.xml所在的包
logging:
  level:
    com.hdd.server.mapper: debug
jwt:
  #jwt存储的请求头
  tokenHeader: Authorization
  #jwt加密使用的密钥
  secret: yeb-secret
  #jwt的超限时间（60*60*24）
  expiration: 604800
  #jwt负载中拿到开头
  tokenHead: Bearer